/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.68
 * Generated at: 2023-01-05 13:11:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jyh.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class insertMember_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>찜꽁</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/jyh/views/insertMember.css\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("    /* ㅇㅇ */\r\n");
      out.write("    .content{\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        height: 500px;\r\n");
      out.write("        background-color: #fff;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<div class=\"wrapper\">\r\n");
      out.write("    <header>\r\n");
      out.write("        <h1 class=\"logo\"><img src=\"/index.markup/img/main_logo.png\" alt=\"\"></h1>\r\n");
      out.write("         <nav class=\"gnb\">\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"/jyh/views/login.jsp\">로그인</a></li>\r\n");
      out.write("                <li><a href=\"/jyh/views/insertMember.jsp\">회원가입</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("         </nav>\r\n");
      out.write("    </header>\r\n");
      out.write("    <section>\r\n");
      out.write("        <div class=\"content\">\r\n");
      out.write("            <div class =\"cont_header\">\r\n");
      out.write("                <h2 id = \"s01\">회원가입</h2>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class = \"content_form\">\r\n");
      out.write("                <form action =\"/member/insert\" method = \"post\" onsubmit=\"return joinform_check()\">\r\n");
      out.write("                    <div id = \"e_form\">\r\n");
      out.write("                    <div class=\"insert_form\">\r\n");
      out.write("                        <b>이메일</b><span name = \"emailCheck\"></span><br>\r\n");
      out.write("                        <input type = \"text\" name = \"email\" maxlength=\"50\" placeholder=\"이메일 형식에 맞게 작성해주세요.\"/>\r\n");
      out.write("                        <button type = \"button\" name = \"checkBtn\" onclick = \"checkingEmail()\">중복확인</button>     \r\n");
      out.write("                        <button type = \"button\" name = \"checkBtn\" onclick = \"new_window()\">인증하기</button>         \r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class = \"insert_form\">\r\n");
      out.write("                        <b>비밀번호</b><span name = \"pwCheck\"></span><br>\r\n");
      out.write("                        <input type = \"password\" name = \"pws\" minlength=\"8\" placeholder=\"(최소8자)1개 이상 숫자,문자포함 특수문자 1개 포함\"/>\r\n");
      out.write("                        \r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class = \"insert_form\">\r\n");
      out.write("                        <b>비밀번호 재확인</b><span name = \"rePwCheck\"></span><br>\r\n");
      out.write("                        <input type = \"password\" name = \"pwRe\" placeholder=\"비밀번호 재설정\"/>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class = \"insert_form\">\r\n");
      out.write("                        <b>닉네임</b><span name = \"nikCheck\"></span><br>\r\n");
      out.write("                        <input type = \"text\" name = \"nik\" placeholder=\"2자 이상 8자 이하 영어,숫자,한글로 구성\"/>\r\n");
      out.write("                    </div>\r\n");
      out.write("                        <div class = \"insert_form\">\r\n");
      out.write("                        <b>연락처</b><span name = \"pCheck\" ></span><br>\r\n");
      out.write("                        <input type = \"text\" name = \"pnum\" placeholder=\"전화번호형식(-포함가능)\"/>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class = \"s_form\">\r\n");
      out.write("                        <b>주소입력</b><span name = \"addrCheck\"></span><br>\r\n");
      out.write("                        <input id=\"member_post\"  type=\"text\" placeholder=\"우편번호 선택\" readonly onclick=\"findAddr()\">\r\n");
      out.write("                        <input id=\"member_addr\" type=\"text\" name = \"addr\" placeholder=\"도로명주소 입력\" readonly> <br>\r\n");
      out.write("                        <input type=\"text\" name = \"detailaddr\" placeholder=\"상세주소 입력\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class = \"insert_form01\">\r\n");
      out.write("                            <input type = \"checkbox\" id = \"check_all\" name = \"check_all\" value = \"1\">\r\n");
      out.write("                            <label for = \"check_all\">  전체 동의</label><br>\r\n");
      out.write("                            <input type = \"checkbox\" id = \"agree01\"  name = \"agree\" value = \"2\">\r\n");
      out.write("                            <label for = \"agree\"><span>(필수)</span> 서비스 이용약관 동의</label><br>\r\n");
      out.write("                            <input type = \"checkbox\" id = \"agree02\" name = \"agree\" value = \"3\">\r\n");
      out.write("                            <label for = \"agree\"><span>(필수)</span> 개인정보 처리 방침 동의</label><br>\r\n");
      out.write("                            <input type = \"checkbox\" id = \"agree03\" name = \"agree\" value = \"4\">\r\n");
      out.write("                            <label for = \"agree\"><b>(선택)</b> 마케팅 메일 수신 동의</label><br>   \r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div id = \"sub_form\">\r\n");
      out.write("                    <input type = \"submit\" id = \"request01\" value = \"가입하기\"/>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <footer>\r\n");
      out.write("        <nav class=\"footer_nav\">\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"#\">서비스 이용약관</a></li>\r\n");
      out.write("                <li><a href=\"#\">개인정보 처리방침</a></li>\r\n");
      out.write("                <li><a href=\"#\">제휴 문의</a></li>\r\n");
      out.write("                <li><a href=\"#\">채용 공고</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </nav>\r\n");
      out.write("        <p class=\"jjim_info\">\r\n");
      out.write("            (주) 찜꽁<br>\r\n");
      out.write("            대표 : 이지원<br>\r\n");
      out.write("            주소 : 서울특별시 마포구 월드컵북로 21 2층 풍성빌딩<br>\r\n");
      out.write("            사업자등록번호 : 202212142126<br>\r\n");
      out.write("            개인정보담당 : service@jjimggong.co.kr\r\n");
      out.write("        </p>\r\n");
      out.write("\r\n");
      out.write("    </footer>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<script src = \"/jyh/views/insertMember.js\" type = \"text/javascript\"></script> \r\n");
      out.write("<script src=\"//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("<script type = \"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
